language: python
services:
    - mysql

matrix:
    include:
        - python: "3.6"
          env: TOXENV=lint
        - python: "2.7"
          env: TOXENV=py27
        - python: "3.5"
          env: TOXENV=py35
        - python: "3.6"
          env: TOXENV=py36
        - python: "3.7"
          env: TOXENV=py37
        - python: "3.8"
          env: TOXENV=py38
        - python: "3.9"
          env: TOXENV=py39

before_install:
  - mysql -e "CREATE DATABASE IF NOT EXISTS zmysqldatest;"
  - mysql -e "CREATE USER 'zmysqldatest'@'localhost' IDENTIFIED BY 'zmysqldatest';"
  - mysql -e "GRANT ALL PRIVILEGES ON zmysqldatest.* TO 'zmysqldatest'@'localhost';"

install:
    - pip install -U pip tox

script:
    - tox

notifications:
    email: false

cache:
  pip: true
  directories:
    - eggs/
