language: python
sudo: false
services:
    - mysql
python:
    - 2.7
    - 3.5
    - 3.6

matrix:
    include:
        - python: "3.7"
          dist: xenial
        - python: "3.8-dev"
          dist: xenial

before_install:
  - mysql -e "CREATE DATABASE IF NOT EXISTS zmysqldatest;"
  - mysql -e "CREATE USER 'zmysqldatest'@'localhost' IDENTIFIED BY 'zmysqldatest';"
  - mysql -e "GRANT ALL PRIVILEGES ON zmysqldatest.* TO 'zmysqldatest'@'localhost';"

install:
    - pip install -U setuptools>=36.2
    - pip install zc.buildout
    - pip install -U coverage coveralls
    - pip install -U six==$(curl $(awk '$1 ==  "extends" {print $3}' buildout.cfg) 2>/dev/null | awk '$1 == "six" {print $3}')
    - buildout bootstrap
    - buildout

script:
    - coverage run bin/test -v1

after_success:
    - coveralls

notifications:
    email: false

cache:
  pip: true
  directories:
    - eggs/
